#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Created on Tue Jan 10 2023

@author: ytirlet, norobert

usage: __main__.py [-h] -d DIRECTORY -t TAXFILE -p PWY_FOLD

Prolipipe pipeline for large-scale assessment of metabolic profiles on bacteria focusing on specific pathways.

options:
  -h, --help            show this help message and exit
  -v, --version         show package version
  -pad PADMET_DIRECTORY, --padmet-dir PADMET_DIRECTORY
                        Path to the merged padmet directory generated by AuFAMe
  -i REACTIONS_TSV, --input-tsv REACTIONS_TSV
                        Path to the reactions.tsv file generated by AuFAMe
  -o OUT_DIR, --outdir OUT_DIR
                        Path to the outdir folder
  -t TAXFILE, --tax TAXFILE
                        Path of the taxon file (.tsv)
  -p PWY_FOLD, --pwy PWY_FOLD
                        Path to the folder with the pathways.txt files for all wanted metabolites.
  -nr, --no-report 
                        Use if you don't want interactive Quarto report.
"""
from __future__ import print_function
from prolipipe.__init__ import __version__
from importlib import resources
import os, shutil
import argparse

from prolipipe import utils, analysis

# FUNCTIONS ---------------------------------------------------------------------------------

def get_report_path():
    with resources.path("prolipipe", "report.qmd") as p:
        return str(p)
    
def parser() : 
    parser = argparse.ArgumentParser(description="Prolipipe pipeline for large-scale assessment of metabolic profiles on bacteria focusing on specific pathways.")
    
    ## arguments 
    parser.add_argument("-pad", "--padmet-dir", dest="padmets", default=argparse.SUPPRESS, help="Path to the merged padmet directory generated by AuFAMe.")
    parser.add_argument("-i", "--input-tsv", dest="reactions", default=argparse.SUPPRESS,help="Path to the reactions.tsv file generated by AuFAMe.")
    parser.add_argument("-o", "--outdir", required=True, dest="outdir",help="Path to the outdir folder.")
    parser.add_argument("-t", "--tax", required=True, dest="taxfile",help="path of the taxon file (.tsv)")
    parser.add_argument("-p", "--pwy", required=True, dest="pwy_fold", help="Path to the folder with the pathways.txt files for all wanted metabolites.")
    parser.add_argument("-nr", "--no-report", dest="no_report", action="store_true", help="Use if you don't want interactive Quarto report.")
    parser.add_argument("-v", "--version", action="version", version=__version__)
    
    return parser.parse_args()

def compare_padmet(input_dir, output_dir):
    """
    Compare padmet files from each annotation tool and create tsv files
    """

    padmet_command = f"""
    mkdir -p {output_dir}/tsv_files
    padmet compare_padmet --padmet={input_dir} --output={output_dir}/tsv_files -v
    """
    try:
        os.system(padmet_command)
        return f"{output_dir}/tsv_files/reactions.tsv"
    except Exception as e:
        print(f"ERROR: can't run compare_padmet with error \n{e}")

def map_pwys_to_GSMs(options) :
    """
        Check "reactions.tsv" file presence, prepare output directory and launch analysis
    """
    taxon_file = options.taxfile
    input_tsv = options.reactions
    outdir = options.outdir
    pwy_dir = options.pwy_fold

    ## check file presence 
    if not os.path.isfile(input_tsv) : 
        raise ValueError(f"ERROR : no reactions.tsv file found in {input_tsv}. Aborting.")
    
    ## output dir generation
    output_metabo = os.path.join(outdir, 'metabo_files')
    utils.mkdir(output_metabo)

    ## launch analysis 
    analysis.generate_res_files(input_tsv, pwy_dir, taxon_file, output_metabo, col_filename="Filename")

    return output_metabo

def render_quarto_report(directory, input_files):
    """
    Render quarto report in the output directory provided to visualise Prolipipe results.
    """
    report_path = get_report_path()

    shutil.copy(report_path, directory)
    os.chdir(directory)
    quarto_command = f"""
    quarto render report.qmd --output-dir quarto_report -P input_dir_name:{input_files}
    """
    os.system(quarto_command)
    os.remove("report.qmd")

# ---------------------------------------------------------------------------------------------

def main():

    ## parsing arguments 
    options = parser()

    # check if inputs are provided
    if "padmets" not in options and "reactions" not in options:
        print("ERROR: Need one input argument: --input-tsv or --padmet-dir")
        return 1

    ## compare padmets if needed
    if "padmets" in options:
        print("\nRun compare padmets")
        options.reactions = compare_padmet(options.padmets, options.outdir)

    ## generate results 
    print("\nSearch for pathways")
    output_metabo = map_pwys_to_GSMs(options)

    if options.no_report:
        return
    
    print("\nCreate Quarto report")
    render_quarto_report(os.path.dirname(output_metabo), os.path.basename(output_metabo))

    print("\nThank you for using Prolipipe !")

def report():
    parser = argparse.ArgumentParser(description="Generate Quarto report for Prolipipe outputs.")
    
    ## arguments 
    parser.add_argument("-d", "--dir", required=True, dest="directory", help="Output path for Quarto report. It needs to contain a directory with tsv files from Prolipipe.")
    parser.add_argument("-i", "--input", required=True, dest="input", help="Name of the directory containing tsv files from Prolipipe.")
    
    options = parser.parse_args()

    render_quarto_report(options.directory, options.input)

if __name__ == "__main__":
    main()
